baseURL = "https://blog.tmrekk.dev"
languageCode = "ja"
title = "tmrekk.dev"
theme = "tale"

pygmentsCodefences = true
pygmentsUseClasses = true

[Author]
    name = "tmrekk"

[menu]
  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    title = "Portfolio"
    url = "https://www.tmrekk.dev"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0

[Params]
    css = ["custom.css"]
